spring.application.name=garderie
server.port=8081
<<<<<<< HEAD
# MySQL config
spring.datasource.url=jdbc:mysql://localhost:3307/garderie_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
=======
spring.profiles.default=mysql
>>>>>>> origin/gestion-transports

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
<<<<<<< HEAD
=======

>>>>>>> origin/gestion-transports
# JWT
application.security.jwt.secret-key=VGlueVNwcmluZ0dhcmRlcmllSldUU2VjcmV0S2V5Rm9yQXV0aGVudGljYXRpb24yMDI2IQ==
application.security.jwt.expiration=86400000

<<<<<<< HEAD
# Uploads (ordonnances PDF)
app.uploads.ordonnances-dir=uploads/ordonnances

# OpenAI (optionnel) - pour suggestions IA des observations
# Recommandé: définir la clé via variable d'environnement ou un fichier local non versionné.
app.openai.api-key=
app.openai.model=gpt-4o-mini
app.openai.reasoning-effort=none
app.openai.timeout-seconds=20

# Upload photos RH
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=uploads/animatrices

# SMTP RH
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=badisstik@gmail.com
spring.mail.password=jotv puvb bcxj obnt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

logging.level.org.springframework.security=DEBUG

# Ollama RH
ollama.api.url=http://localhost:11434/api/generate
ollama.model=tinyspring-rh-v2

# Transport
app.transport.recommandation.distance-max-km=5.0
app.transport.recommandation.rayon-regroupement-km=2.0
app.transport.recommandation.nombre-minimal-demandes-pour-nouveau-trajet=3
app.transport.recommandation.score-texte-minimal=60
app.transport.ai.base-url=http://localhost:8001
app.transport.ai.timeout-seconds=5
=======
app.transport.recommandation.distance-max-km=5.0
app.transport.recommandation.rayon-regroupement-km=2.0
app.transport.recommandation.nombre-minimal-demandes-pour-nouveau-trajet=3
app.transport.recommandation.score-texte-minimal=60

app.transport.ai.base-url=http://localhost:8001
app.transport.ai.timeout-seconds=5
>>>>>>> origin/gestion-transports
