spring.application.name=garderie
server.port=8081

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/garderie_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.profiles.default=mysql

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# JWT
application.security.jwt.secret-key=VGlueVNwcmluZ0dhcmRlcmllSldUU2VjcmV0S2V5Rm9yQXV0aGVudGljYXRpb24yMDI2IQ==
application.security.jwt.expiration=86400000
app.jwt.secret=TinySpringJwtSecretKeyForGarderie2026SecureKey12345
app.jwt.expiration-ms=86400000

# Uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads/animatrices
app.uploads.ordonnances-dir=uploads/ordonnances

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=badisstik@gmail.com
spring.mail.password=jotv puvb bcxj obnt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
app.mail.from=badisstik@gmail.com

# Logs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG
logging.level.jakarta.mail=DEBUG

# IA RH / Observations
app.openai.api-key=
app.openai.model=gpt-4o-mini
app.openai.reasoning-effort=none
app.openai.timeout-seconds=20
ollama.api.url=http://localhost:11434/api/generate
ollama.url=http://localhost:11434
ollama.model=tinyspring-rh-v2

# Evenements
ai.service.events.url=http://localhost:5006

# Transport
app.transport.recommandation.distance-max-km=5.0
app.transport.recommandation.rayon-regroupement-km=2.0
app.transport.recommandation.nombre-minimal-demandes-pour-nouveau-trajet=3
app.transport.recommandation.score-texte-minimal=60
app.transport.ai.base-url=http://localhost:8001
app.transport.ai.timeout-seconds=5

# Boutique
stripe.secret-key=sk_test_51RFbcyCfjTRWhSwVkfBZczyxH8wWaVvmPvencYjT7bm20uiIC7UDqBiWs3l6fgnaiY0QpRiLN6mSvPkt0bnWmx1k00HiWcHCeI
stripe.public-key=pk_test_51RFbcyCfjTRWhSwVjXCYSNAcfr60Ie7nncAnXkksqtrLPwuz0i0YnTt9XebyzumapdM0M4zIzwWUQrPGNkoYLysP00gAWWYcfr
stripe.webhook-secret=whsec_1c743d25ae42bbc1a5697e6aac90d49a04017d924353b3836c3df64d21800544
app.frontend-url=http://localhost:4200
ml.service.url=http://localhost:5001
spring.task.scheduling.enabled=true
server.tomcat.connection-timeout=300000
spring.mvc.async.request-timeout=300000
