spring.datasource.url=${APP_DB_URL:jdbc:mysql://localhost:3306/garderie_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${APP_DB_USERNAME:root}
spring.datasource.password=${APP_DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
