spring.application.name=garderie
server.port=8081
spring.profiles.default=mysql

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# JWT
application.security.jwt.secret-key=VGlueVNwcmluZ0dhcmRlcmllSldUU2VjcmV0S2V5Rm9yQXV0aGVudGljYXRpb24yMDI2IQ==
application.security.jwt.expiration=86400000

app.transport.recommandation.distance-max-km=5.0
app.transport.recommandation.rayon-regroupement-km=2.0
app.transport.recommandation.nombre-minimal-demandes-pour-nouveau-trajet=3
app.transport.recommandation.score-texte-minimal=60

app.transport.ai.base-url=http://localhost:8001
app.transport.ai.timeout-seconds=5
