import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output, SimpleChanges, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../shared/auth.service';
import { Enfant, EnfantService } from '../services/enfant.service';

@Component({
  selector: 'app-animatrice-declarer-changement',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './animatrice-declarer-changement.component.html',
  styleUrl: './animatrice-declarer-changement.component.css'
})
export class AnimatriceDeclarerChangementComponent {
  private readonly enfantService = inject(EnfantService);
  private readonly authService = inject(AuthService);

  @Input({ required: true }) enfants: Enfant[] = [];

  @Output() error = new EventEmitter<string>();
  @Output() success = new EventEmitter<string>();
  @Output() needsReauth = new EventEmitter<boolean>();
  @Output() sent = new EventEmitter<void>();

  private readonly draftKey = 'tinyspring.animatrice.observation.draft';

  isSavingObservation = false;
  isGeneratingObservation = false;

  aiPreview:
    | {
        resume?: string;
        messageParent?: string;
        problemes?: string[];
        contexteRecent?: string[];
        actions?: string[];
        points?: string[];
        questions?: string[];
        signaux?: string[];
      }
    | null = null;

  observationForm = {
    enfantId: 0,
    type: 'SANTE' as string,
    titre: '',
    description: '',
    urgence: 'MOYENNE' as string,
    temperature: null as number | null,
    lieu: '',
    symptomes: '',
    actionsEffectuees: '',
    contexte: ''
  };

  private observationAutoGenerated = true;
  private lastGeneratedSignature = '';
  private lastGeneratedDescription = '';
  private generateTimeoutId: any = null;
  private pendingObservationSend = false;

  public constructor() {
    this.restoreObservationDraft();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['enfants'] && !this.observationForm.enfantId && (this.enfants?.length || 0) > 0) {
      this.observationForm.enfantId = this.enfants[0].id;
    }
  }

  declarerObservation(): void {
    if (this.isSavingObservation) {
      return;
    }

    if (!this.observationForm.enfantId) {
      this.error.emit('Selectionnez un enfant.');
      return;
    }

    if (!this.observationForm.titre.trim()) {
      this.error.emit('Saisissez un titre.');
      return;
    }

    if (!this.observationForm.description.trim()) {
      this.pendingObservationSend = true;
      this.genererDescriptionIA(true);
      this.error.emit('Generation IA en cours...');
      return;
    }

    this.error.emit('');
    this.success.emit('');
    this.isSavingObservation = true;
    this.needsReauth.emit(false);
    this.saveObservationDraft();

    const payload = {
      type: this.observationForm.type,
      titre: this.observationForm.titre.trim(),
      description: this.observationForm.description.trim(),
      observeLe: new Date().toISOString().slice(0, 19),
      urgence: this.observationForm.urgence || null,
      temperature: this.observationForm.temperature,
      lieu: this.observationForm.lieu?.trim() || null,
      symptomes: this.observationForm.symptomes?.trim() || null,
      actionsEffectuees: this.observationForm.actionsEffectuees?.trim() || null
    };

    let req$;
    try {
      req$ = this.enfantService.creerObservationEnfant(this.observationForm.enfantId, payload);
    } catch (e: any) {
      this.error.emit(e?.message || 'Non authentifie (token manquant ou invalide).');
      this.isSavingObservation = false;
      return;
    }

    req$.subscribe({
      next: () => {
        this.success.emit('Observation envoyee aux parents.');
        this.isSavingObservation = false;
        this.pendingObservationSend = false;
        this.clearObservationDraft();
        this.observationForm.titre = '';
        this.observationForm.description = '';
        this.observationForm.temperature = null;
        this.observationForm.lieu = '';
        this.observationForm.symptomes = '';
        this.observationForm.actionsEffectuees = '';
        this.observationForm.contexte = '';
        this.aiPreview = null;
        this.observationAutoGenerated = true;
        this.sent.emit();
      },
      error: (err) => {
        if (err?.status === 401) {
          this.authService.clearSession();
          this.needsReauth.emit(true);
          this.error.emit("Session expiree. Reconnectez-vous pour envoyer l'observation.");
          this.isSavingObservation = false;
          this.pendingObservationSend = false;
          return;
        }
        const status = err?.status != null ? ` (HTTP ${err.status})` : '';
        this.extractHttpErrorDetails(err, (details) => {
          this.error.emit(`Impossible d'envoyer l'observation${status}. ${details}`.trim());
        });
        this.isSavingObservation = false;
        this.pendingObservationSend = false;
      }
    });
  }

  onObservationInputChanged(): void {
    if (!this.observationForm.enfantId || !this.observationForm.type || !this.observationForm.titre?.trim()) {
      return;
    }

    if (!this.observationAutoGenerated && this.observationForm.description?.trim()) {
      return;
    }

    if (this.generateTimeoutId) {
      clearTimeout(this.generateTimeoutId);
    }

    this.generateTimeoutId = setTimeout(() => this.genererDescriptionIA(false), 600);
  }

  onDescriptionChanged(value: string): void {
    if ((value ?? '') !== this.lastGeneratedDescription) {
      this.observationAutoGenerated = false;
    }
  }

  genererDescriptionIA(force = true): void {
    if (this.isGeneratingObservation) {
      return;
    }

    if (!this.observationForm.enfantId) {
      this.error.emit('Selectionnez un enfant.');
      this.pendingObservationSend = false;
      return;
    }

    if (!this.observationForm.type) {
      this.error.emit('Selectionnez un type.');
      this.pendingObservationSend = false;
      return;
    }

    if (!this.observationForm.titre?.trim()) {
      this.error.emit('Saisissez un titre.');
      this.pendingObservationSend = false;
      return;
    }

    if (!force && this.observationForm.titre.trim().length < 4) {
      return;
    }

    const signature = [
      this.observationForm.enfantId,
      this.observationForm.type,
      this.observationForm.titre.trim(),
      this.observationForm.urgence,
      this.observationForm.temperature ?? '',
      this.observationForm.lieu?.trim() ?? '',
      this.observationForm.symptomes?.trim() ?? '',
      this.observationForm.actionsEffectuees?.trim() ?? '',
      this.observationForm.contexte?.trim() ?? ''
    ].join('|');

    if (!force && signature === this.lastGeneratedSignature) {
      return;
    }

    this.lastGeneratedSignature = signature;
    this.isGeneratingObservation = true;
    this.error.emit('');
    this.needsReauth.emit(false);

    const payload = {
      enfantId: this.observationForm.enfantId,
      type: this.observationForm.type,
      titre: this.observationForm.titre.trim(),
      urgence: this.observationForm.urgence || null,
      temperature: this.observationForm.temperature,
      lieu: this.observationForm.lieu?.trim() || null,
      symptomes: this.observationForm.symptomes?.trim() || null,
      actionsEffectuees: this.observationForm.actionsEffectuees?.trim() || null,
      contexte: this.observationForm.contexte?.trim() || null
    };

    let req$;
    try {
      req$ = this.enfantService.genererObservationDescription(payload);
    } catch (e: any) {
      this.error.emit(e?.message || 'Non authentifie (token manquant ou invalide).');
      this.isGeneratingObservation = false;
      this.pendingObservationSend = false;
      return;
    }

    req$.subscribe({
      next: (res) => {
        const desc = res?.description || '';
        if (desc) {
          this.observationForm.description = desc;
          this.lastGeneratedDescription = desc;
          this.observationAutoGenerated = true;
        }
        this.aiPreview = {
          resume: res?.resume || '',
          messageParent: res?.messageParent || '',
          problemes: (res?.problemesPossibles ?? []) as string[],
          contexteRecent: (res?.contexteRecent ?? []) as string[],
          actions: (res?.actionsProposees ?? []) as string[],
          points: (res?.pointsASurveiller ?? []) as string[],
          questions: (res?.questionsAuxParents ?? []) as string[],
          signaux: (res?.signauxDetectes ?? []) as string[]
        };
        this.isGeneratingObservation = false;

        if (this.pendingObservationSend && this.observationForm.description.trim()) {
          this.pendingObservationSend = false;
          this.declarerObservation();
        }
      },
      error: (err) => {
        if (err?.status === 401) {
          this.authService.clearSession();
          this.needsReauth.emit(true);
          this.error.emit("Session expiree. Reconnectez-vous pour generer la description.");
          this.isGeneratingObservation = false;
          this.pendingObservationSend = false;
          return;
        }
        const status = err?.status != null ? ` (HTTP ${err.status})` : '';
        this.extractHttpErrorDetails(err, (details) => {
          this.error.emit(`Impossible de generer la description${status}. ${details}`.trim());
        });
        this.isGeneratingObservation = false;
        this.pendingObservationSend = false;
      }
    });
  }

  private extractHttpErrorDetails(err: any, cb: (details: string) => void): void {
    const defaultMsg = err?.error && typeof err.error === 'string' ? err.error : '';
    if (err?.error instanceof Blob) {
      const reader = new FileReader();
      reader.onload = () => {
        const text = (reader.result as string) || defaultMsg || 'Erreur.';
        cb(text);
      };
      reader.onerror = () => cb(defaultMsg || 'Erreur.');
      reader.readAsText(err.error);
      return;
    }
    cb(defaultMsg || (err?.message ?? 'Erreur.'));
  }

  private saveObservationDraft(): void {
    try {
      const draft = {
        ...this.observationForm
      };
      sessionStorage.setItem(this.draftKey, JSON.stringify(draft));
    } catch {
      // ignore
    }
  }

  private restoreObservationDraft(): void {
    try {
      const raw = sessionStorage.getItem(this.draftKey);
      if (!raw) {
        return;
      }
      const draft = JSON.parse(raw) as any;
      if (!draft) {
        return;
      }
      this.observationForm = {
        ...this.observationForm,
        ...draft
      };
    } catch {
      // ignore
    }
  }

  private clearObservationDraft(): void {
    try {
      sessionStorage.removeItem(this.draftKey);
    } catch {
      // ignore
    }
  }
}

